import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { inflateSync } from "node:zlib";
import { PatchContext } from "../../src/core/patch-context.js";
import { PatchError, TextFile } from "../../src/core/text-file.js";
import type { Target } from "../../src/targets.js";

interface PatchOptions {
	readonly root: string;
	readonly target: Target;
	readonly featureRoot: string;
}

// The words live in lib_ui, where the text of a message and the fields of
// the client are, and the keyboard selection of a message asks them what the
// words of that message are.
const textHeaderPath = "Telegram/lib_ui/ui/text/text.h";
const textSourcePath = "Telegram/lib_ui/ui/text/text.cpp";
const wordsIncludePath = "Telegram/lib_ui/ui/text/text_crossgram_words.inc";
const fieldHeaderPath = "Telegram/lib_ui/ui/widgets/fields/input_field.h";
const fieldSourcePath = "Telegram/lib_ui/ui/widgets/fields/input_field.cpp";
const keyboardSelectionPath =
	"Telegram/SourceFiles/history/view/history_view_keyboard_text_selection.cpp";

// One line of the base64 of the word list holds this many characters, which
// keeps every string literal well below the limit of the compiler.
const base64Line = 4000;

// The declarations of the word segmentation the patched text.cpp implements.
const headerAddition = [
	"",
	"namespace WordSegment {",
	"",
	"\t// Crossgram: the word boundaries of the scripts that write without",
	"\t// spaces between their words, where Qt and the separator list of",
	"\t// this library move over a whole sentence at a time. See",
	"\t// text_crossgram.inc for the words and for the way a run of such",
	"\t// characters is split.",
	"\t//",
	"\t// Every function here reads a string that starts at a multiple of",
	"\t// kChunkLength in the coordinates of its caller, so that a caller",
	"\t// that owns a window of a text instead of the whole text can pass",
	"\t// that window.",
	"\tinline constexpr auto kChunkLength = 64;",
	"",
	"\t[[nodiscard]] bool IsSeparator(const QString &text, int position);",
	"\t[[nodiscard]] int Start(const QString &text, int position);",
	"\t[[nodiscard]] int End(const QString &text, int position);",
	"\t[[nodiscard]] int MoveForward(const QString &text, int position);",
	"\t[[nodiscard]] int MoveBackward(const QString &text, int position);",
	"\t[[nodiscard]] bool IsRightToLeft(const QString &text);",
	"",
	"} // namespace WordSegment",
	"",
].join("\n");

interface Shape {
	readonly search: string;
	readonly replacement: string;
}

// Upstreams differ in the shape of some of the code this patch replaces, so
// every edit lists each shape it knows and fails loudly when none is found,
// which is what an upstream that was rewritten has to do instead of losing
// the patch silently.
function replaceAnyShape(
	file: TextFile,
	marker: string,
	shapes: readonly Shape[],
): void {
	if (file.has(marker)) {
		return;
	}
	const shape = shapes.find((one) => file.has(one.search));
	if (!shape) {
		throw new PatchError(
			`Could not find '${shapes[0]?.search.split("\n")[0]?.trim()}'.`);
	}
	file.replace(shape.search, shape.replacement, marker);
}

interface WordsPayload {
	readonly version: number;
	readonly count: number;
	readonly maxUnits: number;
}

// Reads the word list the generator produced, both to check that it holds
// together and to take the version of its format into the generated source.
function readWords(data: Buffer): WordsPayload {
	if (data.length < 8) {
		throw new PatchError("The generated word list is too short.");
	}
	const payload = inflateSync(data.subarray(4));
	if (payload.length !== data.readUInt32BE(0) || payload.length < 16) {
		throw new PatchError("The generated word list does not unpack.");
	}
	const version = payload.readUInt32LE(0);
	const count = payload.readUInt32LE(4);
	const maxUnits = payload.readUInt32LE(8);
	const offsets = (count + 1) * 4;
	const wordsAt = 16 + offsets + count * 2;
	if (!count
		|| maxUnits > 16
		|| wordsAt > payload.length
		|| payload.readUInt32LE(12 + offsets) !== payload.length - wordsAt) {
		throw new PatchError("The generated word list does not hold together.");
	}
	return { version, count, maxUnits };
}

// The words are packed into one generated source, which the compiler reads
// as a single string literal per line and much faster than as one declaration
// per word.
async function generateWordsInclude(featureRoot: string): Promise<string> {
	const data = await readFile(join(featureRoot, "data/words.bin"));
	const { version, count, maxUnits } = readWords(data);
	const base64 = data.toString("base64");
	const chunks: string[] = [];
	for (let index = 0; index < base64.length; index += base64Line) {
		chunks.push(`\t"${base64.slice(index, index + base64Line)}"`);
	}
	return [
		"// Generated by the Crossgram desktop patcher from",
		"// features/cjk-segmentation/data/words.bin, which is built by",
		"// features/cjk-segmentation/tools/build-dictionary.mjs; see the sources",
		"// recorded in features/cjk-segmentation/data/SOURCES.md. Do not edit.",
		"//",
		`// ${count} words of at most ${maxUnits} UTF-16 units each, packed as the`,
		"// version of the format, the count, the longest word, the score of a",
		"// character the list does not know, and then the offsets of the words,",
		"// the score of each word next to its offset and the words as UTF-8.",
		`static constexpr auto kCrossgramWordsVersion = ${version};`,
		"",
		"static const char kCrossgramWordsBase64[] =\n"
			+ chunks.join("\n") + ";",
		"",
		"static QByteArray CrossgramWordsPayload() {",
		`\treturn qUncompress(QByteArray::fromBase64(QByteArray(`,
		`\t\tkCrossgramWordsBase64)));`,
		"}",
		"",
	].join("\n");
}

async function writeGenerated(
	context: PatchContext,
	relativePath: string,
	contents: string,
): Promise<void> {
	const destination = join(context.root, relativePath);
	await mkdir(dirname(destination), { recursive: true });
	await writeFile(destination, contents, "utf8");
}

export async function patchCjkSegmentation(options: PatchOptions): Promise<void> {
	const context = new PatchContext(
		options.root, options.target, options.featureRoot);

	await context.install(
		"fragments/text_crossgram.inc",
		"Telegram/lib_ui/ui/text/text_crossgram.inc");
	await writeGenerated(
		context, wordsIncludePath, await generateWordsInclude(options.featureRoot));

	const [
		wordsBranch,
		wordsBranchOld,
		wordsBranchNew,
		keyboardWord,
		keyboardWordOld,
		keyboardWordNew,
		fieldWord,
	] = await Promise.all([
		context.fragment("words-branch.cpp"),
		context.fragment("words-branch-old.txt"),
		context.fragment("words-branch-new.txt"),
		context.fragment("keyboard-words.cpp"),
		context.fragment("keyboard-words-old.txt"),
		context.fragment("keyboard-words-new.txt"),
		context.fragment("field-words.cpp"),
	]);

	await context.edit(textHeaderPath, (file) => {
		file.insertBefore(
			"[[nodiscard]] bool IsAlmostLinkEnd(QChar ch);",
			headerAddition,
			"inline constexpr auto kChunkLength = 64;",
		);
	});

	await context.edit(textSourcePath, (file) => {
		file.insertAfter(
			"#include \"ui/text/text.h\"",
			"\n#include \"ui/text/text_crossgram.inc\"",
			"text_crossgram.inc",
		);
		replaceAnyShape(file, "WordSegment::IsSeparator(_text, from)", [
			{ search: wordsBranchOld, replacement: wordsBranch },
			{ search: wordsBranchNew, replacement: wordsBranch },
		]);
	});

	await context.edit(keyboardSelectionPath, (file) => {
		replaceAnyShape(file, "WordSegment::MoveBackward(window, local)", [
			{ search: keyboardWordOld, replacement: keyboardWord },
			{ search: keyboardWordNew, replacement: keyboardWord },
		]);
	});

	await context.edit(fieldHeaderPath, (file) => {
		file.insertAfter(
			"\tvoid mouseMoveEventInner(QMouseEvent *e);",
			"\n\tvoid mouseDoubleClickEventInner(QMouseEvent *e);",
			"void mouseDoubleClickEventInner(QMouseEvent *e);",
		);
		file.insertAfter(
			"\tbool jumpOutOfBlockByBackspace();",
			[
				"",
				"\t// Crossgram: moves over the words of a text that is written without",
				"\t// spaces between them, and grows a double click selection by them.",
				"\tbool handleWordSegmentKey(QKeyEvent *e);",
				"\tbool applyWordSegmentDrag(QMouseEvent *e);",
			].join("\n"),
			"bool applyWordSegmentDrag(QMouseEvent *e);",
		);
		file.insertAfter(
			"\tstd::optional<QTextCursor> _formattingCursorUpdate;",
			[
				"",
				"\t// Crossgram: the word a double click selected, while it is dragged.",
				"\tstd::optional<QTextCursor> _wordSegmentDrag;",
			].join("\n"),
			"std::optional<QTextCursor> _wordSegmentDrag;",
		);
	});

	await context.edit(fieldSourcePath, (file) => {
		file.insertAfter(
			[
				"\tvoid mousePressEvent(QMouseEvent *e) override {",
				"\t\treturn outer()->mousePressEventInner(e);",
				"\t}",
			].join("\n"),
			[
				"\n\tvoid mouseDoubleClickEvent(QMouseEvent *e) override {",
				"\t\treturn outer()->mouseDoubleClickEventInner(e);",
				"\t}",
			].join("\n"),
			"outer()->mouseDoubleClickEventInner(e)",
		);
		file.replace(
			"\tupdateCursorShape();\n\t_inner->QTextEdit::mouseReleaseEvent(e);",
			[
				"\tupdateCursorShape();",
				"\t_wordSegmentDrag = std::nullopt;",
				"\t_inner->QTextEdit::mouseReleaseEvent(e);",
			].join("\n"),
			"_wordSegmentDrag = std::nullopt;",
		);
		file.replace(
			[
				"\t_selectedActionQuoteId = lookupActionQuoteId(e->pos());",
				"\tupdateCursorShape();",
				"\t_inner->QTextEdit::mouseMoveEvent(e);",
			].join("\n"),
			[
				"\t_selectedActionQuoteId = lookupActionQuoteId(e->pos());",
				"\tupdateCursorShape();",
				"\tif (applyWordSegmentDrag(e)) {",
				"\t\treturn;",
				"\t}",
				"\t_inner->QTextEdit::mouseMoveEvent(e);",
			].join("\n"),
			"if (applyWordSegmentDrag(e)) {",
		);
		file.replace(
			[
				"\t} else {",
				"\t\tconst auto text = e->text();",
				"\t\tauto cursor = textCursor();",
			].join("\n"),
			[
				"\t} else if (handleWordSegmentKey(e)) {",
				"\t\t// Crossgram: the step by word was taken above.",
				"\t} else {",
				"\t\tconst auto text = e->text();",
				"\t\tauto cursor = textCursor();",
			].join("\n"),
			"if (handleWordSegmentKey(e)) {",
		);
		file.insertAfterFunction(
			"void InputField::mouseMoveEventInner(QMouseEvent *e)",
			"\n\n" + fieldWord,
			"InputField::handleWordSegmentKey(QKeyEvent *e)",
		);
	});
}
